name: webapp
namespace: cve-processor 

backoffLimit: 4
restartPolicy: OnFailure

container:
  name: webapp-cve-processor
  image: dongrep/webapp_cve_processor
  tag: latest
  imagePullPolicy: Always

imagePullSecrets:
  type: kubernetes.io/dockerconfigjson
  dockerConfig: ZWFzeSB0aGVyZSBoYWNrZXIK

config:
  brokers: webapp-kafka.kafka-cve.svc.cluster.local:9092
  topic: cve
