container:
  name: webapp-cve
  image: dongrep/webapp_cve_processor
  tag: latest
  imagePullPolicy: Always

initcontainer:
  name: db-migrate
  image: dongrep/webapp_db_migrate
  tag: latest
  imagePullPolicy: Always

name: webapp
namespace: webapp-cve-ns

replicas: 1

imagePullSecrets:
  type: kubernetes.io/dockerconfigjson
  dockerConfig: b2theS1tci1oYWNrZXItY2FsbS1kb3duCg==

db_secrets:
  flyway:
    url: amRiYzpwb3N0Z3Jlc3FsOi8vaG9zdC5kb2NrZXIuaW50ZXJuYWw6NTQzMi9jdmUK
    user: cGl5dXNoCg==
    password: YXNkZjEyMzQK
    schema: cve
  type: Opaque

configMap:
  host: host.docker.internal
  db: cve
