name: webapp
namespace: webapp-cve-ns

replicas: 1

container:
  name: webapp-cve
  image: dongrep/webapp_cve_processor
  tag: latest
  imagePullPolicy: Always

initcontainer:
  name: db-migrate
  image: dongrep/webapp_db_migrate
  tag: latest
  imagePullPolicy: Always

imagePullSecrets:
  type: kubernetes.io/dockerconfigjson
  dockerConfig: ZWFzeSB0aGVyZSBoYWNrZXIK

db_secrets:
  flyway:
    password: YXNkZjEyMzQK
  type: Opaque

configMap:
  host: webapp-postgresql.webapp-cve-ns.svc.cluster.local
  db: cve
  flyway:
    url: jdbc:postgresql://webapp-postgresql.webapp-cve-ns.svc.cluster.local:5432/cve
    user: piyush
    schema: cve


postgresql:
  enabled: true
  image:
    tag: 15.5.0-debian-11-r5
  auth:
    username: piyush
    password: asdf1234
    database: cve
  primary:
    persistence:
      size: 1Gi
    labels:
      app: webapp-db
    podLabels:
      app: webapp-db
    resources:
      limits:
        memory: "768Mi"
        cpu: "0.5"
      requests:
        memory: "128Mi"
        cpu: "0.5"
