apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.name }}-configmap
  namespace: {{.Values.namespace }}
data:
  host: {{ .Values.configMap.host }} 
  db: {{ .Values.configMap.db }}
  flyway_url: {{ .Values.configMap.flyway.url }}
  flyway_user: {{ .Values.configMap.flyway.user }}
  flyway_schema: {{ .Values.configMap.flyway.schema }}
