apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name}}
  namespace: {{ .Values.namespace }}
spec:
  # selector:
  #   matchLabels:
  #     app: {{ .Values.name }} 
  # replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }} 
    spec:
      restartPolicy: OnFailure
      initContainers:
      - name: {{ .Values.initcontainer.name }}
        image: {{ .Values.initcontainer.image }}:{{ .Values.initcontainer.tag }}
        imagePullPolicy: {{ .Values.initcontainer.imagePullPolicy }}
        env:
        - name: FLYWAY_URL
          valueFrom:
            configMapKeyRef:
              name: {{.Values.name}}-configmap
              key: flyway_url
        - name: FLYWAY_USER
          valueFrom:
            configMapKeyRef:
              name: {{.Values.name}}-configmap
              key: flyway_user
        - name: FLYWAY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{.Values.name}}-db-secrets
              key: flyway_password
        - name: FLYWAY_DEFAULT_SCHEMA
          valueFrom:
            configMapKeyRef:
              name: {{.Values.name}}-configmap
              key: flyway_schema

      containers:
      - name: {{ .Values.container.name }}
        image: {{ .Values.container.image }}:{{ .Values.container.tag }}
        imagePullPolicy: {{ .Values.container.imagePullPolicy }}
        env:
          - name: HOST
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.name }}-configmap
                key: host
          - name: USER
            valueFrom:
              configMapKeyRef:
                name: {{.Values.name}}-configmap
                key: flyway_user
          - name: PWD
            valueFrom:
              secretKeyRef:
                name: {{.Values.name}}-db-secrets
                key: flyway_password
          - name: DB
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.name }}-configmap
                key: db
              
      imagePullSecrets:
      - name: {{ .Values.name }}-pull-secrets

  backoffLimit: 4
