apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name}}
  namespace: {{ .Values.namespace }}
spec:
  template:
    metadata:
      labels:
        app: {{ .Values.name }} 
    spec:
      restartPolicy: {{ .Values.restartPolicy }}
      containers:
      - name: {{ .Values.container.name }}
        image: {{ .Values.container.image }}:{{ .Values.container.tag }}
        imagePullPolicy: {{ .Values.container.imagePullPolicy }}
        env:
        - name: BROKERS
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.name }}-configmap
              key: brokers
        - name: TOPIC
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.name }}-configmap
              key: topic
                      
      imagePullSecrets:
      - name: {{ .Values.name }}-pull-secrets

  backoffLimit: {{ .Values.backoffLimit }}
