apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Values.namespace }}-cpu-limit-range
spec:
  limits:
  - default:
      cpu: 200m
    defaultRequest:
      cpu: 100m
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Values.namespace }}-mem-limit-range
spec:
  limits:
  - default:
      memory: 300Mi
    defaultRequest:
      memory: 200Mi
    type: Container
